# Generated by Django 4.2.6 on 2023-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0036_candidateurl_present_on_prod_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="current_action_needed",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="collection",
            name="final_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="collection",
            name="indexing_log",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="collection",
            name="spreadsheet_status",
            field=models.IntegerField(
                choices=[
                    (1, "needs curation"),
                    (2, "needs engineering"),
                    (3, "ready to be reindexed on test"),
                    (4, "indexing in progress on test"),
                    (5, "ready to be quality checked on test"),
                    (6, "ready to be deployed to prod"),
                    (7, "indexing in progress on prod"),
                    (8, "ready for final quality check"),
                    (9, "finished!!!"),
                    (10, "ignore"),
                    (11, "need clarification"),
                    (12, "delete from everywhere"),
                    (13, "indexing problem on test"),
                    (14, "indexing problem on prod"),
                    (15, "turn off"),
                    (16, "finished curation"),
                ],
                default=2,
            ),
        ),
    ]
