# Generated by Django 4.2.6 on 2023-11-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0038_merge_20231126_1152"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttypepattern",
            name="pattern_source",
            field=models.IntegerField(
                choices=[(1, "Webapp"), (2, "GitHUb")], default=1
            ),
        ),
        migrations.AddField(
            model_name="excludepattern",
            name="pattern_source",
            field=models.IntegerField(
                choices=[(1, "Webapp"), (2, "GitHUb")], default=1
            ),
        ),
        migrations.AddField(
            model_name="titlepattern",
            name="pattern_source",
            field=models.IntegerField(
                choices=[(1, "Webapp"), (2, "GitHUb")], default=1
            ),
        ),
    ]
