# Generated by Django 4.2.6 on 2023-11-30 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0039_documenttypepattern_pattern_source_and_more"),
        ("sde_collections", "0039_includepattern"),
    ]

    operations = []
