# Generated by Django 4.2.6 on 2023-11-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sde_collections", "0040_merge_20231130_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="includepattern",
            name="pattern_source",
            field=models.IntegerField(
                choices=[(1, "Webapp"), (2, "GitHUb")], default=1
            ),
        ),
    ]
